---
- hosts: all
  vars_files:
  - ../env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a
    ignore_errors: yes

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'
    ignore_errors: yes

  
